version: "3.4"

services:
  nginx:
    build: docker/nginx
    container_name: wea_shop_nginx
    environment:
      DOCKER_HOST: weashop.local
    ports:
      - 80:80
    volumes:
      - ./:/var/www/weashop
    depends_on:
      - php_fpm
    networks:
      - wea_shop

  php_fpm:
    build:
      context: docker/php8_fpm
      args:
        HOST_USERID: ${HOST_USERID}
        HOST_GROUPID: ${HOST_GROUPID}
        GIT_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PASSWORD: ${GIT_PASSWORD}
    container_name: wea_shop_php_fpm
    environment:
      DOCKER_HOST: php_fpm
      PHP_XDEBUG_ENABLED: 0
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
    links:
      - database:host.docker.internal
    depends_on:
      - database
    volumes:
      - ./:/var/www/weashop
    networks:
      - wea_shop

  database:
    image: mariadb:10.6
    container_name: wea_shop_mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=weaShop"
      - "MYSQL_USER=weaShop"
      - "MYSQL_PASSWORD=test"

    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    networks:
      - wea_shop

networks:
  wea_shop: